
[font]
# The normal (roman) font face to use.
normal = { family = "CodeNewRoman Nerd Font", style = "Regular" }
# The bold font face
bold = { family = "CodeNewRoman Nerd Font", style = "Bold" }
# The italic font face
italic = { family = "CodeNewRoman Nerd Font", style = "Italic" }
# Point size of the font
size = 12.0
# Offset is the extra space around each character.
[font.offset]
x = 0
y = 0
# Glyph offset determines the locations of the glyphs within their cells.
[font.glyph_offset]
x = 0
y = 0
