# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: program.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprogram.proto\x12\x07program\"4\n\x0eProgramRequest\x12\x10\n\x08ota_name\x18\x01 \x01(\t\x12\x10\n\x08\x61pp_name\x18\x02 \x01(\t\"\x1f\n\x0cProgramReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x85\x01\n\nProgrammer\x12\x38\n\x08SayHello\x12\x15.program.HelloRequest\x1a\x13.program.HelloReply\"\x00\x12=\n\x07Program\x12\x17.program.ProgramRequest\x1a\x15.program.ProgramReply\"\x00\x30\x01\x42(\n\x10\x66irmware.programB\x0cProgramProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'program_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020firmware.programB\014ProgramProtoP\001\242\002\003HLW'
  _globals['_PROGRAMREQUEST']._serialized_start=26
  _globals['_PROGRAMREQUEST']._serialized_end=78
  _globals['_PROGRAMREPLY']._serialized_start=80
  _globals['_PROGRAMREPLY']._serialized_end=111
  _globals['_HELLOREQUEST']._serialized_start=113
  _globals['_HELLOREQUEST']._serialized_end=141
  _globals['_HELLOREPLY']._serialized_start=143
  _globals['_HELLOREPLY']._serialized_end=172
  _globals['_PROGRAMMER']._serialized_start=175
  _globals['_PROGRAMMER']._serialized_end=308
# @@protoc_insertion_point(module_scope)
