# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import program_pb2 as program__pb2


class ProgrammerStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/program.Programmer/SayHello',
                request_serializer=program__pb2.HelloRequest.SerializeToString,
                response_deserializer=program__pb2.HelloReply.FromString,
                )
        self.Program = channel.unary_stream(
                '/program.Programmer/Program',
                request_serializer=program__pb2.ProgramRequest.SerializeToString,
                response_deserializer=program__pb2.ProgramReply.FromString,
                )


class ProgrammerServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Program(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProgrammerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=program__pb2.HelloRequest.FromString,
                    response_serializer=program__pb2.HelloReply.SerializeToString,
            ),
            'Program': grpc.unary_stream_rpc_method_handler(
                    servicer.Program,
                    request_deserializer=program__pb2.ProgramRequest.FromString,
                    response_serializer=program__pb2.ProgramReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'program.Programmer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Programmer(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/program.Programmer/SayHello',
            program__pb2.HelloRequest.SerializeToString,
            program__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Program(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/program.Programmer/Program',
            program__pb2.ProgramRequest.SerializeToString,
            program__pb2.ProgramReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
